services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_DB
      - MYSQL_USER
      - MYSQL_PASSWORD
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD
      - AWS_REGION
      - AWS_S3_BUCKET
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - JWT_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - LOGGING_FILE_PATH=/var/log/app-logs
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    volumes:
      - app-logs:/var/log/app-logs

  mysqldb:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - backend
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
      - tempo


  loki:
    image: grafana/loki:3.1.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki

  tempo:
    image: grafana/tempo:2.5.0
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo/tempo-config.yml:/etc/tempo.yml
    ports:
      - "3200:3200"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    command: [ "--config=/etc/otelcol-contrib/config.yml" ]
    volumes:
      - ./otel/otel-config.yml:/etc/otelcol-contrib/config.yml
    ports:
      - "4317:4317" # OTLP gRPC endpoint used internally by services
      - "4318:4318" # OTLP HTTP endpoint exposed to Spring App
      - "8889:8889" # Prometheus metrics exporter endpoint
    depends_on:
      - tempo
      - loki

  promtail:
    image: grafana/promtail:3.1.0
    container_name: promtail
    volumes:
      - app-logs:/var/log/app-logs
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki

volumes:
  mysql_data:
  redis_data:
  app-logs:
  grafana_data:
  loki_data:
