services:
    backend:
        build: .
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - mysql_db
            - vault
        command: sh -c './wait-for mysql_db:3306 -- npm start'
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - VAULT_URI=http://vault:8200 # Uses Docker's internal network name to find vault
            - VAULT_TOKEN=${VAULT_ROOT_TOKEN}
    mysql_db:
        image: 'mysql:8.0'
        container_name: local-mysql
        restart: always
        ports:
            - '3307:3306' # Exposes 3306 inside docker to 3307 on your physical host machine
        environment:
            MYSQL_DATABASE: ${MYSQL_DB_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # This must match what you type into Vault!
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # 1. HashiCorp Vault Service
    vault:
        image: hashicorp/vault:1.15.2
        container_name: local-vault
        ports:
            - '8200:8200'
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN} # Static token used ONLY for local dev
            VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
        cap_add:
            - IPC_LOCK # Prevents Vault from swapping memory to disk (good security practice)

