{
 "title": "Logs Observability",
 "tags": [
  "logs",
  "loki"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Log Volumes & Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error and Warning Log Count (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"backend\"} | json | level=\"ERROR\" [1m])) or vector(0)",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(count_over_time({job=\"backend\"} | json | level=\"WARN\" [1m])) or vector(0)",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Total Log volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"backend\"} [1m]))",
     "legendFormat": "Total Logs/min"
    }
   ]
  },
  { "title": "Structured Log Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Live Application Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"backend\"} | json"
    }
   ]
  }
 ]
}