spring:
    application:
        name: bibliophiles-bazar

    # config:
    #     import: optional:vault://secret/bibliophiles-bazar

    # cloud:
    #     vault:
    #         uri: ${VAULT_URI:http://localhost:8200}
    #         token: ${VAULT_TOKEN:root}
    #         kv:
    #             enabled: true
    #             backend: secret
    #             default-context: bibliophiles-bazar
    #         fail-fast: true

    datasource:
        # Use ":-" syntax to provide a default fallback value if the property is missing
        # url: ${vault.db.url:jdbc:mysql://localhost:3306/bibliophiles-bazar}
        # username: ${vault.db.username:root}
        # password: ${vault.db.password:password}
        url: jdbc:mysql://localhost:3306/bibliophiles_bazar
        username: root
        password: adarshmelath1305_
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 10
            minimum-idle: 5

    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: false

    mail:
        host: smtp.gmail.com
        port: 587
        username:bibliophilesbazar@gmail.com
        password: 
        properties:
            '[mail.smtp.auth]': true
            '[mail.smtp.starttls.enable]': true

app:
    jwt:
        secret: JWT_SECRET=B1b1l0ph1l3sBaz4r$3cr3tK3y2024!XyZ@9
        expiration: 900000 # 15 minutes
        refresh-expiration: 604800000 # 7 days
        frontend-url: http://localhost:5174
