spring:
    application:
        name: bibliophiles-bazar
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
    config:
        import: "vault://"
    cloud:
        vault:
            uri: ${VAULT_URI:http://localhost:8200}
            token: ${VAULT_TOKEN:root}
            kv:
                enabled: true
                backend: secret # Sets up standard Vault Key-Value engine path
                default-context: "bibliophiles-bazar" 

