name: Lint Commit messages
on:
  push:
    branches:
      - main
      - develop
permissions:
  contents: read
  pull-requests: read

jobs:
  commit-lint:
    name: Verify Conventional Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Commit Messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.yml